# Alternative GNU Make project makefile autogenerated by Premake, modified by hand
ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

SHELLTYPE := posix
ifeq (.exe,$(findstring .exe,$(ComSpec)))
	SHELLTYPE := msdos
endif

# Configurations
# #############################################
CC=emcc
OPTIMISE := -O3
SETTINGS = -s USE_SDL=2 -s USE_PTHREADS=1
INCLUDES += -Isrc -Itests -Ivendor/stb
TARGETDIR = bin/webassembly/NES-Emulator
TARGET = $(TARGETDIR)/NES-Emulator.html
OBJDIR = bin-int/webassembly/NES-Emulator
ALL_CFLAGS += $(INCLUDES) $(OPTIMISE) $(SETTINGS) -s WASM=1

# File sets
# #############################################

GENERATED :=
OBJECTS :=

GENERATED += $(OBJDIR)/2A03.o
GENERATED += $(OBJDIR)/2C02.o
GENERATED += $(OBJDIR)/2C02_Bus.o
GENERATED += $(OBJDIR)/6502.o
GENERATED += $(OBJDIR)/6502_Bus.o
GENERATED += $(OBJDIR)/Audio.o
GENERATED += $(OBJDIR)/Benchmarks.o
GENERATED += $(OBJDIR)/Cartridge.o
GENERATED += $(OBJDIR)/FileDialog.o
GENERATED += $(OBJDIR)/Gamepad.o
GENERATED += $(OBJDIR)/Gui.o
GENERATED += $(OBJDIR)/MapperUtils.o
GENERATED += $(OBJDIR)/Mapper_000.o
GENERATED += $(OBJDIR)/Mapper_001.o
GENERATED += $(OBJDIR)/Mapper_002.o
GENERATED += $(OBJDIR)/Mapper_003.o
GENERATED += $(OBJDIR)/Mapper_JUN.o
GENERATED += $(OBJDIR)/Renderer.o
GENERATED += $(OBJDIR)/main.o
GENERATED += $(OBJDIR)/nes.o
GENERATED += $(OBJDIR)/stb_imp.o
GENERATED += $(OBJDIR)/string_util.o
GENERATED += $(OBJDIR)/test_2C02.o
GENERATED += $(OBJDIR)/test_6502.o
GENERATED += $(OBJDIR)/test_util.o
GENERATED += $(OBJDIR)/timer.o
OBJECTS += $(OBJDIR)/2A03.o
OBJECTS += $(OBJDIR)/2C02.o
OBJECTS += $(OBJDIR)/2C02_Bus.o
OBJECTS += $(OBJDIR)/6502.o
OBJECTS += $(OBJDIR)/6502_Bus.o
OBJECTS += $(OBJDIR)/Audio.o
OBJECTS += $(OBJDIR)/Benchmarks.o
OBJECTS += $(OBJDIR)/Cartridge.o
OBJECTS += $(OBJDIR)/FileDialog.o
OBJECTS += $(OBJDIR)/Gamepad.o
OBJECTS += $(OBJDIR)/Gui.o
OBJECTS += $(OBJDIR)/MapperUtils.o
OBJECTS += $(OBJDIR)/Mapper_000.o
OBJECTS += $(OBJDIR)/Mapper_001.o
OBJECTS += $(OBJDIR)/Mapper_002.o
OBJECTS += $(OBJDIR)/Mapper_003.o
OBJECTS += $(OBJDIR)/Mapper_JUN.o
OBJECTS += $(OBJDIR)/Renderer.o
OBJECTS += $(OBJDIR)/main.o
OBJECTS += $(OBJDIR)/nes.o
OBJECTS += $(OBJDIR)/stb_imp.o
OBJECTS += $(OBJDIR)/string_util.o
OBJECTS += $(OBJDIR)/test_2C02.o
OBJECTS += $(OBJDIR)/test_6502.o
OBJECTS += $(OBJDIR)/test_util.o
OBJECTS += $(OBJDIR)/timer.o

# Rules
# #############################################

all: $(TARGET)
	@:

$(TARGET): $(GENERATED) $(OBJECTS) | $(TARGETDIR)
	@echo Linking NES-Emulator
	$(SILENT) $(CC) $(OPTIMISE) -o $@ $(OBJECTS) $(SETTINGS) --preload-file Consola.ttf --preload-file roms

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJECTS): | $(OBJDIR)

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning NES-Emulator
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -rf $(TARGETDIR)
	$(SILENT) rm -rf $(GENERATED)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(GENERATED)) rmdir /s /q $(subst /,\\,$(GENERATED))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

# File Rules
# #############################################

$(OBJDIR)/2A03.o: src/Backend/2A03.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/2C02.o: src/Backend/2C02.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/2C02_Bus.o: src/Backend/2C02_Bus.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/6502.o: src/Backend/6502.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/6502_Bus.o: src/Backend/6502_Bus.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Cartridge.o: src/Backend/Cartridge.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Gamepad.o: src/Backend/Gamepad.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/MapperUtils.o: src/Backend/Mappers/MapperUtils.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Mapper_000.o: src/Backend/Mappers/Mapper_000.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Mapper_001.o: src/Backend/Mappers/Mapper_001.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Mapper_002.o: src/Backend/Mappers/Mapper_002.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Mapper_003.o: src/Backend/Mappers/Mapper_003.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Mapper_JUN.o: src/Backend/Mappers/Mapper_JUN.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/nes.o: src/Backend/nes.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/FileDialog.o: src/FileDialog.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Audio.o: src/Frontend/Audio.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Gui.o: src/Frontend/Gui.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) -o "$@"  -c "$<"
$(OBJDIR)/Renderer.o: src/Frontend/Renderer.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/main.o: src/main.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/stb_imp.o: src/stb_imp.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/string_util.o: src/string_util.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/timer.o: src/timer.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) -o "$@"  -c "$<"
$(OBJDIR)/Benchmarks.o: tests/Benchmarks.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) -o "$@"  -c "$<"
$(OBJDIR)/test_2C02.o: tests/test_2C02.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) -o "$@" -c "$<"
$(OBJDIR)/test_6502.o: tests/test_6502.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) -o "$@"  -c "$<"
$(OBJDIR)/test_util.o: tests/test_util.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) -o "$@" -c "$<"
